title = "zébresse, zébrelle, zébrette : Quel feminin pour zèbre ?"
description = "Une recherche sur les trois termes, leurs fréquences et leurs ethymologies."
lang = "fr"
date = "2026-05-27"
date-update = "2026-05-31"
