title = "The horse that was disguised as Twilight Sparkle"
lang = "en"
date = "2026-10-04"
description = "Research on the horse disguised as Twilight Sparkle video (during the 80cm Cosplay show Jumping). Also Rainbow Dash."